### PR TITLE
cica-apply-for-compensation-production

### PR DESCRIPTION
**Pull request by ermiasworku**

### CODE REVIEW

**Comment by ermiasworku** [comment]
@digitalronin  Hi, 

Can you please provide an assistance moving my namespace to live-1

Thanks,

**Comment by digitalronin** [comment]
> Can you please provide an assistance moving my namespace to live-1

I've moved the files into the live-1 cluster namespaces directory, so that's where your namespaces will be created when the PR is merged.

There seems to be a mistake in this file:

https://github.com/ministryofjustice/cloud-platform-environments/blob/cica-apply-for-compenstation-production/namespaces/live-1.cloud-platform.service.justice.gov.uk/cica-apply-for-compenstation-uat/01-rbac.yaml

The group name is incorrect. Looking at the production version, it should probably be `github:cica` Please could you change it?

https://github.com/ministryofjustice/cloud-platform-environments/blob/cica-apply-for-compenstation-production/namespaces/live-1.cloud-platform.service.justice.gov.uk/cica-apply-for-compenstation-production/01-rbac.yaml

**Comment by ermiasworku** [comment]
@digitalronin  I have now changed the group name. Can you please review it.

**Comment by ermiasworku** [comment]
@digitalronin Can you please advise who is going to merge to master ?

**Comment by digitalronin** [comment]
> @digitalronin Can you please advise who is going to merge to master ?

give me a moment, please - this PR has gotten a bit messy. Once I've tidied it up, I'll approve it, and then you can merge it.

**Comment by digitalronin** [comment]
This branch has gotten a bit messed up, with commits added from rebases that don't belong here. I've opened a new PR #551 containing the changes that belong in this PR, so I'm closing this one.

**Comment by digitalronin** [comment]
@ermiasworku #551 has been approved and merged, so your namespaces should appear in live-1 shortly (within 20 minutes or so), once the build pipeline has completed.

**Pull request closed without merging**
