### PR TITLE
Track a Query - Add new environments

### PR DESCRIPTION
**Pull request by mseedat-moj**
Adds all required environments for migrating the `correspondence_tool_staff` application (Track a Query)

### CODE REVIEW

**Comment by digitalronin** [comment]
@mseedat-moj You've got "is-production" set to true in an lot of your elasticache.tf files, too.

**Comment by digitalronin** [comment]
Both production and staging rds.tf have "is-production" true

**Comment by digitalronin** [comment]
demo, production and staging s3.tf have is-production true

**Comment by mseedat-moj** [comment]
@digitalronin - yes I wasn't sure what the repercussions of setting things to 'is production' to true was - where I thought we need to mimic production as closely as possible (e.g. demo, staging, production) I set `is-production: true` - advice welcome.

**Pull request merged**
