### PR TITLE
tag aws-resource with namespace name

### PR DESCRIPTION
**Pull request by pwyborn**
Why: [Tag all AWS resources with namespace name#2348](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2348)

### CODE REVIEW

**Review by vijay-veeranki — APPROVED** [review]

**Comment by digitalronin** [comment]
@pwyborn can this be merged?

**Comment by pwyborn** [comment]
Hi @digitalronin - David- this one can be merged - however not giving  me the option to? Is there something in the pipeline stopping it?

**Comment by digitalronin** [comment]
@pwyborn sometimes the concourse actions just get stuck. Closing and reopening the PR sometimes helps, as does pushing a null change (like adding a blank line to a file), although that will also dismiss any reviews.

The brute force option is to temporarily disable branch protection while you merge.

**Comment by pwyborn** [comment]
Cannot get this one to clear multi-namespace - so opening a new pull request

**Pull request closed without merging**
