### PR TITLE
🔥 PIC-637 - Remove DynamoDB from court-probation-preprod

### PR DESCRIPTION
**Pull request by jhevans**

### CODE REVIEW

**Comment by digitalronin** [comment]
There's an issue with the dynamodb module and "embedded" providers. Delete the dynamodb table using a targeted `terraform destroy` before merging this PR.

**Comment by jhevans** [comment]
@digitalronin I've not had to use Terraform directly previously so not sure how to go about that, is there some documentation on how to get set up?

**Comment by digitalronin** [comment]
@jhevans Sorry, that was a note for the CP team! I'm about to take care of this now - I just put the note in case anyone else in the team was planning to handle this before I could.

**Review by digitalronin — APPROVED** [review]

**Comment by digitalronin** [comment]
I'll merge this PR myself, after I delete the dynamodb table using a manual `terraform destroy`

**Comment by jhevans** [comment]
@digitalronin Oh good, that's a relief 😅  I'm always up for learning new stuff but manual updates to cloud-platform infra does not appeal! 😆

**Comment by jhevans** [comment]
@digitalronin I'll raise the prod ticket as well since that will follow on the heels of this

**Comment by digitalronin** [comment]
I've destroyed the dynamodb table

**Pull request merged**
