### PR TITLE
PIC-637 - Remove DynamoDB

### PR DESCRIPTION
**Pull request by jhevans**

### CODE REVIEW

**Review by digitalronin — CHANGES_REQUESTED** [review]
You need to keep the `provider` stanza.

I'd suggest putting just that part into a `main.tf` file.

**Comment by jhevans** [comment]
@digitalronin thanks for the heads up re the provider! Have updated

**Comment by digitalronin** [comment]
@jhevans `terraform plan` is still failing for this - I'm not sure why. I've asked the team, and we're looking into it.

**Comment by digitalronin** [comment]
@jhevans The providers for this resource were a bit messed up, so we've deleted the dynamodb instance via a manual terraform apply, and we'll merge another PR that leaves the code in this folder in a sensible state. Sorry this took a while.

**Comment by jhevans** [comment]
@digitalronin ah right, thanks for letting me know, can I consider that done and applied then? Was the issue anything to do with how we've built it? If there's anything we can do to avoid such problems in future I'm always eager to learn 😄

**Comment by digitalronin** [comment]
@jhevans No, it's because we forked an existing dynamodb terraform provider, which included a custom provider definition inside the module. That's not how we do things anymore, so terraform thought there was a missing provider when it tried to delete the resource, absent the code that defines the resource. We ran a `terraform destroy` targeting the dynamodb table, and everything is fine again.

We might run into the same problem if you're deleting dynamodb from staging/prod too though.

**Comment by jhevans** [comment]
@digitalronin Funny you should say that 😬  - https://github.com/ministryofjustice/cloud-platform-environments/pull/3687

**Pull request closed without merging**
