### PR TITLE
add wildcard certificates to formbuilder envs

### PR DESCRIPTION
**Pull request by asmega**

### CODE REVIEW

**Comment by asmega** [comment]
fyi when this get merged there will need to be a manual step in AWS. i believe to setup the dns zones?

**Comment by asmega** [comment]
hmm merging is still blocked. is it because you are using a different github account?

**Comment by asmega** [comment]
that worked. thank you!

**Comment by razvan-moj** [comment]
> hmm merging is still blocked. is it because you are using a different github account?

yes, was in the wrong browser

**Pull request merged**
