### PR TITLE
Create cica staging namespace claim-criminal-injuries-compensation-stg

### PR DESCRIPTION
**Pull request by pkpaulk**

### CODE REVIEW

**Comment by pkpaulk** [comment]
Hi David,

Thanks for pointing this out, reverted the changes and updated staging configs should be only in the new respective namespace folder.

Cheers,

Paul

**Comment by pkpaulk** [comment]
Sorry, now committed those change if you wanted to x reference.

From: Paul Kraszewski
Sent: 17 June 2019 17:20
To: ministryofjustice/cloud-platform-environments <reply@reply.github.com>; ministryofjustice/cloud-platform-environments <cloud-platform-environments@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [ministryofjustice/cloud-platform-environments] Create cica staging namespace claim-criminal-injuries-compensation-stg (#899)

Hi David,

Thanks for pointing this out, reverted the changes and updated staging configs should be only in the new respective namespace folder.

Cheers,

Paul

**Comment by digitalronin** [comment]
Is this PR still required, or should we close it?

**Comment by pkpaulk** [comment]
Hi David,

I just did a git status
`nothing to commit, working tree clean’

So I’ve not added ecr.tf and done the push on that so I can get a pipeline happening to this environment.

Kind regards,

Paul

**Comment by pkpaulk** [comment]
I have created a new request #920 after updating some name changes required by our org. If you could please close #899

**Pull request closed without merging**
