### PR TITLE
Create cccd api-sandbox namespace with ECR

### PR DESCRIPTION
**Pull request by kmahern**
Create cccd api-sandbox namespace and ecr in live0

### CODE REVIEW

**Comment by colinbruce** [comment]
Thanks @digitalronin... back to the drawing board on getting our template deploy builds working with https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#podsecuritypolicy 

This PR will return in live-1! :)

**Comment by digitalronin** [comment]
> Thanks @digitalronin... back to the drawing board on getting our template deploy builds working with https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#podsecuritypolicy

Please let us know if there's anything we can do to help.

**Comment by colinbruce** [comment]
You may regret that offer @digitalronin :D

**Comment by kmahern** [comment]
Hi, have moved this to live-1, if you are happy please can it be approved. Thanks!

**Comment by digitalronin** [comment]
Is this PR still required, or shall I close it?

**Pull request closed without merging**
