### PR TITLE
Increase BaSM staging memory limit on pods

### PR DESCRIPTION
**Pull request by martyn-w**
this increases the memory limit from 500mb to 1gb, as we are having some memory issues on our staging system

### CODE REVIEW

**Review by digitalronin — APPROVED** [review]

**Comment by martyn-w** [comment]
holding off merging this change in for the moment

**Review by smoothcontract — COMMENTED** [review]
LGTM 👍

**Comment by willfish** [comment]
LGTM, too

**Comment by martyn-w** [comment]
re-opening after further consideration

**Review by digitalronin — APPROVED** [review]

**Pull request merged**
