### PR TITLE
Adds our legacy staging S3 resource to user-policy to allow one-way sync.

### PR DESCRIPTION
**Pull request by EarthlingDavey**
We intend to sync from a source S3 bucket `intranet2-staging-storage-h1d4c9820k0u`, owned by a different AWS account.

Following the [Migrate from existing buckets guide](https://github.com/ministryofjustice/cloud-platform-terraform-s3-bucket#migrate-from-existing-buckets), I understand that the source bucket must be added to the `user_policy` here.

This PR adds the relevant change to our s3 resource definition.

cc: @EmilyHazlehurst @wilson1000

### CODE REVIEW

**Review by wilson1000 — COMMENTED** [review]
Hi Davey, this policy will need to reference the AWS account the bucket is in, otherwise it will default to CloudPlatform.

**Comment by EarthlingDavey** [comment]
@wilson1000 thanks !

I'm also not sure this PR will go through, possibly `user_policy` is deprecated.

**Comment by EarthlingDavey** [comment]
Hi Cloud Platform, we still require a review on this please.

### CDPT. Do not merge!

@EmilyHazlehurst @wilson1000 . We/I need to trouble-shoot why `wp-offload-media` stopped working since yesterday. Let's not add this variable into the mix yet.

**Comment by EmilyHazlehurst** [comment]
> ### CDPT. Do not merge!
> @EmilyHazlehurst @wilson1000 . We/I need to trouble-shoot why `wp-offload-media` stopped working since yesterday. Let's not add this variable into the mix yet.

@EarthlingDavey I can't access our pods anymore: `Error from server (Forbidden): pods is forbidden` - I wonder if that's related?

**Pull request merged**
